apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: degencast-namespace-prod
  name: degencast-frames-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: degencast-frames
  template:
    metadata:
      labels:
        app: degencast-frames
    spec:
      containers:
        - name: degencast-frames
          image: 272372497786.dkr.ecr.us-east-1.amazonaws.com/degencast-frames:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_FRAMES_BASE_URL
              value: "https://frames.degencast.wtf"
            - name: NEXT_PUBLIC_DEGENCAST_WEB_URL
              value: "https://degencast.wtf"
            - name: NEXT_PUBLIC_DEGENCAST_API
              value: "https://api.u3.xyz"
            - name: NEXT_PUBLIC_FEE_RECIPIENT_WALLET_ADDRESS
              value: "0x1AF3b65FFa0222c447DD4373299071F945EB36A2"
            - name: NEXT_PUBLIC_API_KEY_0X_API_KEY
              value: "edaf2c5d-be24-4415-a675-195aa9f3ac6a"
            - name: NEXT_PUBLIC_BUY_TOKEN_PERCENTAGE_FEE
              value: "0.003"
            - name: NEXT_PUBLIC_SWAPTOKEN_LEADERBOARD
              value: "https://degencast.wtf"
            - name: NEXT_PUBLIC_NEYNAR_API_KEY
              value: 976F5E1F-03AA-4BCC-81B2-CB80BB6F844A
            - name: NEXT_PUBLIC_FARCASTER_HUB_URL
              value: "https://hub-api.neynar.com"
            - name: NEXT_PUBLIC_TRADE_TOKEN_VIEWMORE
              value: "https://dev.degencast.xyz/channels/tokens"
            - name: NEXT_PUBLIC_TRADE_TOKEN_LEADERBOARD
              value: "https://dev.degencast.xyz/channels/tokens"
            - name: NEXT_PUBLIC_BASE_NETWORK
              value: "sepolia"
            - name: NEXT_PUBLIC_DEGEN_ADDRESS
              value: "0xD084FD38BB7fDba38b0a2BffbA9e558ce29Ad8AC"
            - name: NEXT_PUBLIC_CURATION_FACTORY_ADDRESS
              value: "0x6232cb5ba5bf3b7932d56e3938af4b54e2ef5dab"
            - name: NEXT_PUBLIC_UNISWAP_QUOTEV2_ADDRESS
              value: "0xC5290058841028F1614F3A6F0F5816cAd0df5E27"
