apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: degencast-namespace-prod
  name: degencast-frames-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: degencast-frames
  template:
    metadata:
      labels:
        app: degencast-frames
    spec:
      containers:
        - name: degencast-frames
          image: 272372497786.dkr.ecr.us-east-1.amazonaws.com/degencast-frames:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "4Gi"  # 请求的内存
            limits:
              memory: "8Gi"  # 限制的内存
          ports:
            - containerPort: 3000
          env:
            - name: FRAMES_BASE_URL
              value: "https://frames.degencast.wtf"
            - name: DEGENCAST_WEB_URL
              value: "https://degencast.wtf"
            - name: DEGENCAST_API
              value: "https://api.u3.xyz"
            - name: FEE_RECIPIENT_WALLET_ADDRESS
              value: "0x1AF3b65FFa0222c447DD4373299071F945EB36A2"
            - name: API_KEY_0X_API_KEY
              value: "edaf2c5d-be24-4415-a675-195aa9f3ac6a"
            - name: BUY_TOKEN_PERCENTAGE_FEE
              value: "0.003"
            - name: SWAPTOKEN_LEADERBOARD
              value: "https://degencast.wtf"
            - name: NEYNAR_API_KEY
              value: 976F5E1F-03AA-4BCC-81B2-CB80BB6F844A
            - name: FARCASTER_HUB_URL
              value: "https://hub-api.neynar.com"
            - name: TRADE_TOKEN_VIEWMORE
              value: "https://dev.degencast.xyz/channels/tokens"
            - name: TRADE_TOKEN_LEADERBOARD
              value: "https://dev.degencast.xyz/channels/tokens"
            - name: BASE_NETWORK
              value: "main"
            - name: DEGEN_ADDRESS
              value: "0x4ed4E862860beD51a9570b96d89aF5E1B0Efefed"
            - name: CURATION_FACTORY_ADDRESS
              value: "0x29442Fa1926c81b0A64A40030a96C462E483Ec93"
            - name: UNISWAP_QUOTEV2_ADDRESS
              value: "0x3d4e44Eb1374240CE5F1B871ab261CD16335B76a"
            - name: OPENSEA_BASE_URL
              value: https://testnets.opensea.io/assets/base-sepolia
            - name: CURATION_ACTION_LINK
              value: https://warpcast.com/~/add-cast-action?url=https://frames.degencast.wtf/cast-actions/vote

